# Generated by hand for MetricsService (grpcio-tools not available in this env).
# Source: proto/metrics.proto

import grpc

from . import metrics_pb2 as metrics__pb2


class MetricsServiceStub:
    """Stub for MetricsService."""

    def __init__(self, channel):
        self.StreamMetrics = channel.stream_unary(
            "/meshml.metrics.MetricsService/StreamMetrics",
            request_serializer=metrics__pb2.MetricPoint.SerializeToString,
            response_deserializer=metrics__pb2.MetricsAck.FromString,
        )


class MetricsServiceServicer:
    """Servicer interface for MetricsService."""

    async def StreamMetrics(self, request_iterator, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MetricsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StreamMetrics": grpc.stream_unary_rpc_method_handler(
            servicer.StreamMetrics,
            request_deserializer=metrics__pb2.MetricPoint.FromString,
            response_serializer=metrics__pb2.MetricsAck.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "meshml.metrics.MetricsService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
