# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metrics.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmetrics.proto\x12\x0emeshml.metrics\"t\n\x0bMetricPoint\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0c\n\x04step\x18\x02 \x01(\x03\x12\x0c\n\x04loss\x18\x03 \x01(\x02\x12\x10\n\x08\x61\x63\x63uracy\x18\x04 \x01(\x02\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\x12\x11\n\tworker_id\x18\x06 \x01(\t\".\n\nMetricsAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\\\n\x0eMetricsService\x12J\n\rStreamMetrics\x12\x1b.meshml.metrics.MetricPoint\x1a\x1a.meshml.metrics.MetricsAck(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICPOINT']._serialized_start=33
  _globals['_METRICPOINT']._serialized_end=149
  _globals['_METRICSACK']._serialized_start=151
  _globals['_METRICSACK']._serialized_end=197
  _globals['_METRICSSERVICE']._serialized_start=199
  _globals['_METRICSSERVICE']._serialized_end=291
# @@protoc_insertion_point(module_scope)
