# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import parameter_server_pb2 as parameter__server__pb2


class ParameterServerStub(object):
    """Parameter Server Service - Gradient aggregation and model weight distribution
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWeights = channel.unary_unary(
                '/meshml.parameter_server.ParameterServer/GetWeights',
                request_serializer=parameter__server__pb2.WeightsRequest.SerializeToString,
                response_deserializer=parameter__server__pb2.WeightsResponse.FromString,
                )
        self.UpdateGradients = channel.unary_unary(
                '/meshml.parameter_server.ParameterServer/UpdateGradients',
                request_serializer=parameter__server__pb2.GradientsUpdate.SerializeToString,
                response_deserializer=parameter__server__pb2.GradientsAck.FromString,
                )
        self.GetOptimizerState = channel.unary_unary(
                '/meshml.parameter_server.ParameterServer/GetOptimizerState',
                request_serializer=parameter__server__pb2.OptimizerStateRequest.SerializeToString,
                response_deserializer=parameter__server__pb2.OptimizerStateResponse.FromString,
                )
        self.GetModelVersion = channel.unary_unary(
                '/meshml.parameter_server.ParameterServer/GetModelVersion',
                request_serializer=parameter__server__pb2.VersionRequest.SerializeToString,
                response_deserializer=parameter__server__pb2.VersionResponse.FromString,
                )


class ParameterServerServicer(object):
    """Parameter Server Service - Gradient aggregation and model weight distribution
    """

    def GetWeights(self, request, context):
        """Worker fetches current model weights
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGradients(self, request, context):
        """Worker sends computed gradients
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOptimizerState(self, request, context):
        """Worker fetches optimizer state (Adam momentum, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelVersion(self, request, context):
        """Get current model version
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParameterServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeights,
                    request_deserializer=parameter__server__pb2.WeightsRequest.FromString,
                    response_serializer=parameter__server__pb2.WeightsResponse.SerializeToString,
            ),
            'UpdateGradients': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGradients,
                    request_deserializer=parameter__server__pb2.GradientsUpdate.FromString,
                    response_serializer=parameter__server__pb2.GradientsAck.SerializeToString,
            ),
            'GetOptimizerState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOptimizerState,
                    request_deserializer=parameter__server__pb2.OptimizerStateRequest.FromString,
                    response_serializer=parameter__server__pb2.OptimizerStateResponse.SerializeToString,
            ),
            'GetModelVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelVersion,
                    request_deserializer=parameter__server__pb2.VersionRequest.FromString,
                    response_serializer=parameter__server__pb2.VersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meshml.parameter_server.ParameterServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ParameterServer(object):
    """Parameter Server Service - Gradient aggregation and model weight distribution
    """

    @staticmethod
    def GetWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meshml.parameter_server.ParameterServer/GetWeights',
            parameter__server__pb2.WeightsRequest.SerializeToString,
            parameter__server__pb2.WeightsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateGradients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meshml.parameter_server.ParameterServer/UpdateGradients',
            parameter__server__pb2.GradientsUpdate.SerializeToString,
            parameter__server__pb2.GradientsAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOptimizerState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meshml.parameter_server.ParameterServer/GetOptimizerState',
            parameter__server__pb2.OptimizerStateRequest.SerializeToString,
            parameter__server__pb2.OptimizerStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModelVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meshml.parameter_server.ParameterServer/GetModelVersion',
            parameter__server__pb2.VersionRequest.SerializeToString,
            parameter__server__pb2.VersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
