# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import model_registry_pb2 as model__registry__pb2


class ModelRegistryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterModel = channel.unary_unary(
                '/meshml.model_registry.ModelRegistry/RegisterModel',
                request_serializer=model__registry__pb2.RegisterModelRequest.SerializeToString,
                response_deserializer=model__registry__pb2.RegisterModelResponse.FromString,
                )
        self.FinalizeModelUpload = channel.unary_unary(
                '/meshml.model_registry.ModelRegistry/FinalizeModelUpload',
                request_serializer=model__registry__pb2.FinalizeModelUploadRequest.SerializeToString,
                response_deserializer=model__registry__pb2.FinalizeModelUploadResponse.FromString,
                )
        self.GetModelArtifact = channel.unary_unary(
                '/meshml.model_registry.ModelRegistry/GetModelArtifact',
                request_serializer=model__registry__pb2.GetModelArtifactRequest.SerializeToString,
                response_deserializer=model__registry__pb2.GetModelArtifactResponse.FromString,
                )
        self.GetFinalModelDownloadUrl = channel.unary_unary(
                '/meshml.model_registry.ModelRegistry/GetFinalModelDownloadUrl',
                request_serializer=model__registry__pb2.GetFinalModelDownloadUrlRequest.SerializeToString,
                response_deserializer=model__registry__pb2.GetFinalModelDownloadUrlResponse.FromString,
                )
        self.UploadCheckpoint = channel.unary_unary(
                '/meshml.model_registry.ModelRegistry/UploadCheckpoint',
                request_serializer=model__registry__pb2.CheckpointUploadRequest.SerializeToString,
                response_deserializer=model__registry__pb2.CheckpointUploadResponse.FromString,
                )
        self.UploadFinalModel = channel.unary_unary(
                '/meshml.model_registry.ModelRegistry/UploadFinalModel',
                request_serializer=model__registry__pb2.FinalModelUploadRequest.SerializeToString,
                response_deserializer=model__registry__pb2.FinalModelUploadResponse.FromString,
                )


class ModelRegistryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeModelUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFinalModelDownloadUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFinalModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModel,
                    request_deserializer=model__registry__pb2.RegisterModelRequest.FromString,
                    response_serializer=model__registry__pb2.RegisterModelResponse.SerializeToString,
            ),
            'FinalizeModelUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeModelUpload,
                    request_deserializer=model__registry__pb2.FinalizeModelUploadRequest.FromString,
                    response_serializer=model__registry__pb2.FinalizeModelUploadResponse.SerializeToString,
            ),
            'GetModelArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelArtifact,
                    request_deserializer=model__registry__pb2.GetModelArtifactRequest.FromString,
                    response_serializer=model__registry__pb2.GetModelArtifactResponse.SerializeToString,
            ),
            'GetFinalModelDownloadUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFinalModelDownloadUrl,
                    request_deserializer=model__registry__pb2.GetFinalModelDownloadUrlRequest.FromString,
                    response_serializer=model__registry__pb2.GetFinalModelDownloadUrlResponse.SerializeToString,
            ),
            'UploadCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadCheckpoint,
                    request_deserializer=model__registry__pb2.CheckpointUploadRequest.FromString,
                    response_serializer=model__registry__pb2.CheckpointUploadResponse.SerializeToString,
            ),
            'UploadFinalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFinalModel,
                    request_deserializer=model__registry__pb2.FinalModelUploadRequest.FromString,
                    response_serializer=model__registry__pb2.FinalModelUploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meshml.model_registry.ModelRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModelRegistry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meshml.model_registry.ModelRegistry/RegisterModel',
            model__registry__pb2.RegisterModelRequest.SerializeToString,
            model__registry__pb2.RegisterModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FinalizeModelUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meshml.model_registry.ModelRegistry/FinalizeModelUpload',
            model__registry__pb2.FinalizeModelUploadRequest.SerializeToString,
            model__registry__pb2.FinalizeModelUploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModelArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meshml.model_registry.ModelRegistry/GetModelArtifact',
            model__registry__pb2.GetModelArtifactRequest.SerializeToString,
            model__registry__pb2.GetModelArtifactResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFinalModelDownloadUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meshml.model_registry.ModelRegistry/GetFinalModelDownloadUrl',
            model__registry__pb2.GetFinalModelDownloadUrlRequest.SerializeToString,
            model__registry__pb2.GetFinalModelDownloadUrlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meshml.model_registry.ModelRegistry/UploadCheckpoint',
            model__registry__pb2.CheckpointUploadRequest.SerializeToString,
            model__registry__pb2.CheckpointUploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadFinalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meshml.model_registry.ModelRegistry/UploadFinalModel',
            model__registry__pb2.FinalModelUploadRequest.SerializeToString,
            model__registry__pb2.FinalModelUploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
