# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from meshml_worker.proto import task_orchestrator_pb2 as task__orchestrator__pb2


class TaskOrchestratorStub(object):
    """Task Orchestrator Service - Worker lifecycle and task management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/meshml.orchestrator.TaskOrchestrator/RegisterWorker',
                request_serializer=task__orchestrator__pb2.WorkerCapabilities.SerializeToString,
                response_deserializer=task__orchestrator__pb2.WorkerRegistration.FromString,
                )
        self.SendHeartbeat = channel.unary_unary(
                '/meshml.orchestrator.TaskOrchestrator/SendHeartbeat',
                request_serializer=task__orchestrator__pb2.Heartbeat.SerializeToString,
                response_deserializer=task__orchestrator__pb2.HeartbeatAck.FromString,
                )
        self.RequestTask = channel.unary_unary(
                '/meshml.orchestrator.TaskOrchestrator/RequestTask',
                request_serializer=task__orchestrator__pb2.TaskRequest.SerializeToString,
                response_deserializer=task__orchestrator__pb2.TaskAssignment.FromString,
                )
        self.ReportBatchComplete = channel.unary_unary(
                '/meshml.orchestrator.TaskOrchestrator/ReportBatchComplete',
                request_serializer=task__orchestrator__pb2.BatchCompletion.SerializeToString,
                response_deserializer=task__orchestrator__pb2.BatchAck.FromString,
                )
        self.ReportBatchFailed = channel.unary_unary(
                '/meshml.orchestrator.TaskOrchestrator/ReportBatchFailed',
                request_serializer=task__orchestrator__pb2.BatchFailure.SerializeToString,
                response_deserializer=task__orchestrator__pb2.BatchAck.FromString,
                )


class TaskOrchestratorServicer(object):
    """Task Orchestrator Service - Worker lifecycle and task management
    """

    def RegisterWorker(self, request, context):
        """Worker registers with the system and provides capabilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Worker sends periodic heartbeat to indicate it's alive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestTask(self, request, context):
        """Worker requests tasks to execute
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportBatchComplete(self, request, context):
        """Worker reports batch completion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportBatchFailed(self, request, context):
        """Worker reports batch failure
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=task__orchestrator__pb2.WorkerCapabilities.FromString,
                    response_serializer=task__orchestrator__pb2.WorkerRegistration.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=task__orchestrator__pb2.Heartbeat.FromString,
                    response_serializer=task__orchestrator__pb2.HeartbeatAck.SerializeToString,
            ),
            'RequestTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestTask,
                    request_deserializer=task__orchestrator__pb2.TaskRequest.FromString,
                    response_serializer=task__orchestrator__pb2.TaskAssignment.SerializeToString,
            ),
            'ReportBatchComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportBatchComplete,
                    request_deserializer=task__orchestrator__pb2.BatchCompletion.FromString,
                    response_serializer=task__orchestrator__pb2.BatchAck.SerializeToString,
            ),
            'ReportBatchFailed': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportBatchFailed,
                    request_deserializer=task__orchestrator__pb2.BatchFailure.FromString,
                    response_serializer=task__orchestrator__pb2.BatchAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meshml.orchestrator.TaskOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskOrchestrator(object):
    """Task Orchestrator Service - Worker lifecycle and task management
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meshml.orchestrator.TaskOrchestrator/RegisterWorker',
            task__orchestrator__pb2.WorkerCapabilities.SerializeToString,
            task__orchestrator__pb2.WorkerRegistration.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meshml.orchestrator.TaskOrchestrator/SendHeartbeat',
            task__orchestrator__pb2.Heartbeat.SerializeToString,
            task__orchestrator__pb2.HeartbeatAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meshml.orchestrator.TaskOrchestrator/RequestTask',
            task__orchestrator__pb2.TaskRequest.SerializeToString,
            task__orchestrator__pb2.TaskAssignment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportBatchComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meshml.orchestrator.TaskOrchestrator/ReportBatchComplete',
            task__orchestrator__pb2.BatchCompletion.SerializeToString,
            task__orchestrator__pb2.BatchAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportBatchFailed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/meshml.orchestrator.TaskOrchestrator/ReportBatchFailed',
            task__orchestrator__pb2.BatchFailure.SerializeToString,
            task__orchestrator__pb2.BatchAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
